import { ComponentProps, ReactNode } from '../../../../node_modules/react';
import { ControllerStateAndHelpers } from 'downshift';
import { default as FieldText } from '../../fieldText';
import { AutocompleteMenu } from '../common/autocompleteMenu';
import { DownshiftStore, MultipleDownshiftProps } from './multipleDownshift';
import { GetItemPropsT } from '../types';

export interface MultipleAutocompleteProps<T> {
    options: T[];
    loading: boolean;
    onStateChange: MultipleDownshiftProps<T>['onStateChange'];
    value: T[];
    placeholder: string;
    error: string | boolean;
    touched: boolean;
    creatable: boolean;
    editable: boolean;
    renderOption?: (value: T, index: number, isNew: boolean, getItemProps: GetItemPropsT<T>) => ReactNode;
    onChange: (selectedItems: T | T[] | null, downshift: ControllerStateAndHelpers<T> | null) => void;
    onFocus: () => void;
    onBlur: () => void;
    disabled: boolean;
    mobileDisabled: boolean;
    inputProps: ComponentProps<typeof FieldText>;
    parseValueToString: (value: T | null) => string;
    minLength?: number | null;
    maxLength?: number | null;
    async?: boolean;
    customClass: string;
    createWithoutConfirmation: boolean;
    getItemValidationErrorType?: (item: T) => string;
    clearItemsError: () => void;
    isDropdownMode?: boolean;
    getAdditionalCreationCondition: (value: string) => boolean;
    highlightUnStoredItem: boolean;
    parseInputValueFn: ((value: string) => T[]) | null;
    handleUnStoredItemCb: ((newSelectedItems: DownshiftStore<T>, prevSelectedItems: DownshiftStore<T>) => void) | null;
    dataAutomationId?: string;
    existingItemsMap: Record<string | number, boolean>;
    optionVariant: ComponentProps<typeof AutocompleteMenu>['optionVariant'];
    customizeNewSelectedValue: (value: T) => T;
    renderCustomSelectedItem?: (item: T) => ReactNode;
    getUniqKey?: (item: T) => string;
    customEmptyListMessage?: string;
    customNoMatchesMessage?: string;
    useFixedPositioning?: boolean;
    newItemButtonText?: string;
    menuClassName?: string;
}
export declare const MultipleAutocomplete: <T>(componentsProps: MultipleAutocompleteProps<T>) => import("react/jsx-runtime").JSX.Element;
